version: 2.1

jobs:
  # TODO deploy up-to-date cheatsheet
  deploy:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run: python generate-cheatsheet.py
  # TODO Generate cheatsheet and check it matches checked-in version
  # TODO Check all terraform is valid and formatted
  test:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run: python generate-cheatsheet.py

workflows:
  test_and_deploy:
    jobs:
      - test
      # - deploy:
      #     requires:
      #       - test
