version: 2.1

jobs:
  # TODO deploy up-to-date cheatsheet
  deploy:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run: python scripts/generate-cheatsheet.py
  # TODO Generate cheatsheet and check it matches checked-in version
  # TODO Check all terraform is valid and formatted
  test_cheatsheet_generation:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run:
          name: linting
          command: |
            pip install flake8
            flake8
      - run:
          name: check_cheatsheet_generation
          command: |
            python scripts/generate-cheatsheet.py > test-cheatsheet.md
            diff test-cheatsheet.md cheatsheet.md
  test_tf_examples:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run:
          name: install tfswitch
          command: curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | bash
      - run:
          name: install terraform at correct version
          command: |
            cd examples/terraform
            tfswitch
            cd ../..
      - run:
          name: check
          command: scripts/check-terraform-examples.sh

workflows:
  test_and_deploy:
    jobs:
      - test_cheatsheet_generation
      - test_tf_examples
      # - deploy:
      #     requires:
      #       - test
