version: 2.1

jobs:
  # TODO deploy up-to-date cheatsheet
  deploy:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run: python generate-cheatsheet.py
  # TODO Generate cheatsheet and check it matches checked-in version
  # TODO Check all terraform is valid and formatted
  test_cheatsheet_generation:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run:
          name: linting
          command: |
            pip install flake8
            flake8
      - run:
          name: check_cheatsheet_generation
          command: |
            python generate-cheatsheet.py > test-cheatsheet.md
            diff test-cheatsheet.md cheatsheet.md
  test_tf_examples:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run: echo "TODO"

workflows:
  test_and_deploy:
    jobs:
      - test_cheatsheet_generation
      - test_tf_examples
      # - deploy:
      #     requires:
      #       - test
